config/routes.rb
Fifteenaside::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :counties

  resources :clubs

  resources :profiles

  resources :venues

  resources :users

  

   root :to => 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :about, :football, :hurling, :profileable_id, :profileable_type
  belongs_to :profileable, :polymorphic => true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :football %><br />
    <%= f.check_box :football %>
  </div>
  <div class="field">
    <%= f.label :hurling %><br />
    <%= f.check_box :hurling %>
  </div>
  <div class="field">
    <%= f.label :profileable_id %><br />
    <%= f.number_field :profileable_id %>
  </div>
  <div class="field">
    <%= f.label :profileable_type %><br />
    <%= f.text_field :profileable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>About</th>
    <th>Football</th>
    <th>Hurling</th>
    <th>Profileable</th>
    <th>Profileable type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.about %></td>
    <td><%= profile.football %></td>
    <td><%= profile.hurling %></td>
    <td><%= profile.profileable_id %></td>
    <td><%= profile.profileable_type %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>About:</b>
  <%= @profile.about %>
</p>

<p>
  <b>Football:</b>
  <%= @profile.football %>
</p>

<p>
  <b>Hurling:</b>
  <%= @profile.hurling %>
</p>

<p>
  <b>Profileable:</b>
  <%= @profile.profileable_id %>
</p>

<p>
  <b>Profileable type:</b>
  <%= @profile.profileable_type %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>