config/routes.rb
Fifteenaside::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :counties

  resources :clubs

  resources :profiles

  resources :venues

  resources :users

  

   root :to => 'home#index'

end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :name
  has_one :profile, :as => :profileable
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  # GET /counties
  # GET /counties.json
  def index
    @counties = County.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @counties }
    end
  end

  # GET /counties/1
  # GET /counties/1.json
  def show
    @county = County.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @county }
    end
  end

  # GET /counties/new
  # GET /counties/new.json
  def new
    @county = County.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @county }
    end
  end

  # GET /counties/1/edit
  def edit
    @county = County.find(params[:id])
  end

  # POST /counties
  # POST /counties.json
  def create
    @county = County.new(params[:county])

    respond_to do |format|
      if @county.save
        format.html { redirect_to @county, notice: 'County was successfully created.' }
        format.json { render json: @county, status: :created, location: @county }
      else
        format.html { render action: "new" }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /counties/1
  # PUT /counties/1.json
  def update
    @county = County.find(params[:id])

    respond_to do |format|
      if @county.update_attributes(params[:county])
        format.html { redirect_to @county, notice: 'County was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counties/1
  # DELETE /counties/1.json
  def destroy
    @county = County.find(params[:id])
    @county.destroy

    respond_to do |format|
      format.html { redirect_to counties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/_form.html.erb
<%= form_for(@county) do |f| %>
  <% if @county.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
      <% @county.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counties/edit.html.erb
<h1>Editing county</h1>

<%= render 'form' %>

<%= link_to 'Show', @county %> |
<%= link_to 'Back', counties_path %>

app/views/counties/index.html.erb
<h1>Listing counties</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @counties.each do |county| %>
  <tr>
    <td><%= county.name %></td>
    <td><%= link_to 'Show', county %></td>
    <td><%= link_to 'Edit', edit_county_path(county) %></td>
    <td><%= link_to 'Destroy', county, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New County', new_county_path %>

app/views/counties/new.html.erb
<h1>New county</h1>

<%= render 'form' %>

<%= link_to 'Back', counties_path %>

app/views/counties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @county.name %>
</p>


<%= link_to 'Edit', edit_county_path(@county) %> |
<%= link_to 'Back', counties_path %>