config/routes.rb
Fifteenaside::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :counties

  resources :clubs

  resources :profiles

  resources :venues

  resources :users

  

   root :to => 'home#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :lat, :long
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <tr>
    <th>Lat</th>
    <th>Long</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venues.each do |venue| %>
  <tr>
    <td><%= venue.lat %></td>
    <td><%= venue.long %></td>
    <td><%= link_to 'Show', venue %></td>
    <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
    <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @venue.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @venue.long %>
</p>


<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>